# -*- coding: utf-8 -*-
#"""Untitled3.ipynb

#Automatically generated by Colab.

#Original file is located at
    #https://colab.research.google.com/drive/1Lp2Eq4kutajFk6EN5Xm0NYJYcme2unrf
"""
#на это ругается впс, поэтому комментим
#!pip install pytelegrambotapi
#!pip install --upgrade requests urllib3

import requests
import urllib3
import telebot
from telebot import types
import random
import os
from dotenv import load_dotenv

# запускаем + добавляем чтоб читалось енв с токеном, токен нигде не светим
load_dotenv()
TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
bot = telebot.TeleBot(TOKEN)

# картиночки для рандома
images = [
    'https://noisy-haze-abcf.fbmorpathologic.workers.dev/AgACAgIAAyEFAAMBBpO4TAAD_mqBipk6E2Pvn8THMRQgJA9eLevbAAIbHWsbrBIISJQq2eRSYteoAQADAgADeAADPQQ.jpg',
    'https://noisy-haze-abcf.fbmorpathologic.workers.dev/AgACAgIAAyEFAAMBBpO4TAAD7mqBiVkX38m8-4Clm5JBloIIopqdAAINHWsbrBIISNv5kgm_LnPfAQADAgADeAADPQQ.jpg',
    'https://noisy-haze-abcf.fbmorpathologic.workers.dev/AgACAgIAAyEFAAMBBpO4TAAD72qBiVl6c6Q9C0RBSi3h8UKEWDfkAAIOHWsbrBIISLukmtqqk4OpAQADAgADeAADPQQ.jpg',
    'https://noisy-haze-abcf.fbmorpathologic.workers.dev/AgACAgIAAyEFAAMBBpO4TAAD8WqBiVk9FxlDsZNnZmClVtH2hvRJAAIQHWsbrBIISIqRSVqB9AmRAQADAgADeAADPQQ.jpg',
    'https://noisy-haze-abcf.fbmorpathologic.workers.dev/AgACAgIAAyEFAAMBBpO4TAAD8mqBiVlid8NKXBZw3ZjoOwlc6-UtAAIRHWsbrBIISIdpcXIdJrakAQADAgADeAADPQQ.jpg',
    'https://noisy-haze-abcf.fbmorpathologic.workers.dev/AgACAgIAAyEFAAMBBpO4TAAD82qBiVmkjfgy7Ae9pjorYY1525MAAxIdaxusEghIBUkAAYEjEDpoAQADAgADeAADPQQ.jpg',
    'https://noisy-haze-abcf.fbmorpathologic.workers.dev/AgACAgIAAyEFAAMBBpO4TAAD9GqBiVkKUciKdE_s1P2RouHFuTGgAAITHWsbrBIISC8ZFA_r5X6MAQADAgADeAADPQQ.jpg'
]

# погнали наши городских
@bot.message_handler(commands=["start"])
def start(m, res=False):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    item1 = types.KeyboardButton("Верстаю!")
    item2 = types.KeyboardButton("Вот прям выкладываю!")
    markup.add(item1, item2)

    bot.send_message(m.chat.id, 'Ну? Чем ты сейчас занимаешься?', reply_markup=markup)

# это для множественных кнопок
def show_options(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    options = ["Картинка", "Спойлер", "Видео", "Кнопка", "Назад"]
    markup.add(*[types.KeyboardButton(option) for option in options])
    bot.send_message(message.chat.id, 'Для чего нужен код?', reply_markup=markup)

# поехали вопросы задавать
@bot.message_handler(content_types=["text"])
def handle_text(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)  

    if message.text.strip() == 'Верстаю!':
        show_options(message)

    elif message.text.strip() == 'Картинка':
        bot.send_message(message.chat.id, '<div align="center"><p class="veryhighimg"><a class="veryhighimg" href="ссылка на картинку-полноразмер1" rel="nofollow"><img src="ссылка на превью картинки1" alt="img" /></a><a class="veryhighimg" href="ссылка на полноразмер картинки2" rel="nofollow"><img src="сылка на превью картинки2" alt="img" /></a></div>')
        bot.send_message(message.chat.id, 'НЕ ЗАБУДЬ СКИН! Этот код работает только со скином.')
        show_options(message)  

    elif message.text.strip() == 'Спойлер':
        bot.send_message(message.chat.id, '<details><summary>подпись ката</summary></details>')
        show_options(message)  

    elif message.text.strip() == 'Видео':
        bot.send_message(message.chat.id, '<div class="videocontainer"><div class="videoscale"><iframe class="mobilevideo" src="ссылка на видео" width="560" height="315" frameborder="0" allowfullscreen=""></iframe></div></div>')
        bot.send_message(message.chat.id, 'НЕ ЗАБУДЬ СКИН! Этот код работает только со скином.')
        show_options(message)  

    elif message.text.strip() == 'Кнопка':
        bot.send_message(message.chat.id, '<p align ="center"><a href="линк" class="button1" rel="nofollow">надпись на кнопке</a></p>')
        bot.send_message(message.chat.id, 'НЕ ЗАБУДЬ СКИН! Этот код работает только со скином.')
        show_options(message)  

    elif message.text.strip() == 'Назад':
        start(message) 

    elif message.text.strip() == 'Вот прям выкладываю!':
        bot.send_message(message.chat.id, 'ПОГНАЛИ НАШИ ГОРОДСКИХ! Начинаем проверять.')
        bot.send_message(message.chat.id, 'Заголовок норм? Там не надо случайно добавить упоминание про арт-крафт-итд?')
        item1 = types.KeyboardButton("С заголовком всё норм!")
        item2 = types.KeyboardButton("Ой, точно")
        markup.add(item1, item2)
        bot.send_message(message.chat.id, 'Выбери вариант!', reply_markup=markup)

    elif message.text.strip() == 'Ой, точно':
        bot.send_message(message.chat.id, 'Добавляй!')
        markup.add(types.KeyboardButton("С заголовком всё норм!")) 
        bot.send_message(message.chat.id, 'Нажми, когда добавишь:', reply_markup=markup)

    elif message.text.strip() == 'С заголовком всё норм!':
        bot.send_message(message.chat.id, 'Умничка!') 
        item1 = types.KeyboardButton("Проверено!")
        item2 = types.KeyboardButton("Ой, ща я быстро")
        markup.add(item1, item2)
        bot.send_message(message.chat.id, 'А мегабайты проверить?', reply_markup=markup)

    elif message.text.strip() == 'Ой, ща я быстро':
        bot.send_message(message.chat.id, 'Добавляй! Надо посмотреть в браузере network, чтоб наверняка.')
        markup.add(types.KeyboardButton("Всё проверено!"))  # Добавляем только кнопку "раз"
        bot.send_message(message.chat.id, 'Нажми, когда проверишь:', reply_markup=markup)

    elif message.text.strip() in ['Проверено!', 'Всё проверено!']: #тут уебански потому что я не понял в чем ошибка
        bot.send_message(message.chat.id, 'Отлично!!')  
        item1 = types.KeyboardButton("Всё чётенько!")
        item2 = types.KeyboardButton("Да в рот компот!")
        markup.add(item1, item2)
        bot.send_message(message.chat.id, 'В предупреждениях чузнота не перепутана с отсутствием ворнингов?', reply_markup=markup)

    elif message.text.strip() == 'Да в рот компот!':
        bot.send_message(message.chat.id, 'Давай, пока никто не видит')
        markup.add(types.KeyboardButton("Исправлено!"))  
        bot.send_message(message.chat.id, 'Жмакни, когда сделаешь', reply_markup=markup)

    elif message.text.strip() in ['Всё чётенько!', 'Исправлено!']:
        bot.send_message(message.chat.id, 'Шикардос, держи звёздочку🌟')
        instrunt = (
            "мибблы от М до E / от R до NC-17 и выше – 2 работы – fk26_me_mibbles\n"
            "\n"
            "визуал от М до E / от R до NC-17 и выше – 1 работа – fk26_me_visual\n"
            "\n"
            "миди от М до E / от R до NC-17 и выше – 1 работа – fk26_me_midi\n"
            "\n"
            "спецквест – 1 работа –  fk26_sp1 и/или fk26_sp2"
        ) # пишем отдельно, чтоб нам не растудошило код
        bot.send_message(message.chat.id, instrunt)  
        item1 = types.KeyboardButton("В правильной!")
        item2 = types.KeyboardButton("Фу ты ну ты!")
        markup.add(item1, item2)
        bot.send_message(message.chat.id, 'Вот шпаргалка по коллекциям. В правильной лежит?', reply_markup=markup)

    elif message.text.strip() == 'Фу ты ну ты!':
        bot.send_message(message.chat.id, 'Да я сам их всегда путаю')
        markup.add(types.KeyboardButton("Готово!"))  
        bot.send_message(message.chat.id, 'Готово?', reply_markup=markup)

    elif message.text.strip() in ['В правильной!', 'Готово!']:
        bot.send_message(message.chat.id, 'Ура! Замечательно!')  
        item1 = types.KeyboardButton("Есть, правильная!")
        item2 = types.KeyboardButton("Есть на жопе шерсть!(((")
        markup.add(item1, item2)
        bot.send_message(message.chat.id, 'Внутренняя коллекция есть? Правильная?', reply_markup=markup)

    elif message.text.strip() == 'Есть на жопе шерсть!(((':
        bot.send_message(message.chat.id, 'Поправь пока')
        markup.add(types.KeyboardButton("Коллекция стоит!"))  
        bot.send_message(message.chat.id, 'Готово?', reply_markup=markup)

    elif message.text.strip() in ['Есть, правильная!', 'Коллекция стоит!']:
        bot.send_message(message.chat.id, 'Чуть-чуть осталось!')  
        item1 = types.KeyboardButton("Конечно!")
        item2 = types.KeyboardButton("Бляаааааа")
        markup.add(item1, item2)
        bot.send_message(message.chat.id, 'Командный псевдоним правильный?', reply_markup=markup)

    elif message.text.strip() == 'Бляаааааа':
        bot.send_message(message.chat.id, 'Кромо по жопе надаёт!')
        markup.add(types.KeyboardButton("Исправлено!!"))  
        bot.send_message(message.chat.id, 'Исправлено??', reply_markup=markup)

    elif message.text.strip() in ['Конечно!', 'Исправлено!!']:
        bot.send_message(message.chat.id, 'И по мелочи!') 
        item1 = types.KeyboardButton("Как тот хуй!")
        item2 = types.KeyboardButton("Ничего у меня не стоит")
        markup.add(item1, item2)
        bot.send_message(message.chat.id, 'Скин стоит?', reply_markup=markup)

    elif message.text.strip() == 'Ничего у меня не стоит':
        bot.send_message(message.chat.id, 'Поставь на всякий случай!')
        markup.add(types.KeyboardButton("Готово!!!"))  
        bot.send_message(message.chat.id, 'Готово??', reply_markup=markup)

    elif message.text.strip() in ['Как тот хуй!', 'Готово!!!']:
        bot.send_message(message.chat.id, 'Всё! Отлично поработали! Ты лучше всех! Держи картинку!')
        random_image = random.choice(images)
        bot.send_photo(message.chat.id, random_image)
        bot.send_message(message.chat.id, 'Возвращаемся в начало!')  
        start(message)

# и он сказал поехали и махнул рукой
bot.polling(none_stop=True, interval=0)
